branches:
  except:
  - gh-pages

language: ruby
rvm:
  - 3.2

cache:
  bundler: true
  directories:
    - vendor/bundler

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer

before_install:
  - make doctor

install:
  - make install

script:
  - make all

after_success: >
  echo $TRAVIS_BRANCH; echo $TRAVIS_PULL_REQUEST;
  if [[ $TRAVIS_BRANCH == 'main' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    # Generate HTML
    make build ;
    # Configure Git with Travis CI information
    git config --global user.email "travis@travis-ci.org" ;
    git config --global user.name "travis-ci" ;
    # Delete the current repository
    rm -rf .git ;
    # Rebuild the repository from the generated files and push to GitHub pages
    cd _site ;
    git init ;
    git add . ;
    git commit -m "Deploy Travis CI build $TRAVIS_BUILD_NUMBER to GitHub pages" ;
    git push -f https://x-access-token:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} master:gh-pages ;
  fi

notifications:
  email:
    on_success: never
    on_failure: change
