# Settings

exclude:
  - README.md
  - Makefile
  - Gemfile*
  - vendor/

paginate:   5

markdown:     kramdown
highlighter:  rouge
permalink:  pretty
plugins:
  - jekyll-paginate
  - jekyll-redirect-from

# Routes

url:        https://jacebrowning.info
baseurl:    /
downloads:  /downloads
assets:     /assets

# Content

title:          Jace Browning
tagline:        Software Craftsman
description:    I build tools that empower developers to ship quality code as fast as possible.

repo: https://github.com/jacebrowning/jacebrowning.info

author:
  name:           Jace Browning
  twitter:        https://twitter.com/jacebrowning
  linkedin:       https://www.linkedin.com/in/jacebrowning
  github:         https://github.com/jacebrowning
  stackoverflow:  https://stackoverflow.com/users/429533/jace-browning
  speakerdeck:    https://speakerdeck.com/jacebrowning

# Options

show_resume: true
